services:
  database:
    container_name: 'postgres'
    image: postgres:15
    environment:
      - POSTGRES_DB=blps_bank
      - POSTGRES_USER=mariia
      - POSTGRES_PASSWORD=5432
    ports:
      - '5432:5432'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge